stages:
  - build
  - test
  - deploy

docker_build:
  stage: build
  image: reg.mikumikumi.xyz/base/kaniko-builder
  variables:
    BUILD_DOCKERFILE: dockerfile
  script:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - dockerfile
        - requirements.txt
        - scripts/install_ubuntu_deps.sh
        - scripts/mysql_dump.sql
        - scripts/postgres_dump.sql
        - scripts/sqlite_dump.sql
      when: never

docker_build_manual:
  stage: build
  image: reg.mikumikumi.xyz/base/kaniko-builder
  when: manual
  variables:
    BUILD_DOCKERFILE: dockerfile
  script:
    - build

gtest:
  stage: test
  image: $CI_REGISTRY/libsese/sese-core:latest
  allow_failure: true
  when: always
  script:
    # config cmake project
    - cmake
      -G Ninja
      -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja
      -DCMAKE_C_COMPILER=/usr/bin/gcc
      -DCMAKE_CXX_COMPILER=/usr/bin/g++
      -Bbuild/linux-release
      -DCMAKE_BUILD_TYPE=Release
      -DSESE_BUILD_TEST=ON
      -DSESE_USE_NATIVE_MANAGER=ON
      -DSESE_USE_ARCHIVE=ON
      -DSESE_DB_USE_SQLITE=ON
      -DSESE_DB_USE_MARIADB=ON
      -DSESE_DB_USE_POSTGRES=ON
      -DSESE_DB_SQLITE_CONNECTION_STRING="/tmp/db_test.db"
      -DSESE_DB_MYSQL_CONNECTION_STRING="host=127.0.0.1\;port=3306\;user=root\;pwd=libsese\;db=db_test\;"
      -DSESE_DB_PSQL_CONNECTION_STRING="host=127.0.0.1\;port=5432\;user=root\;pwd=libsese\;db=db_test\;"
      -DCMAKE_CXX_FLAGS="--coverage -fprofile-update=atomic"
    - cmake --build build/linux-release -- -j 2
    # setup service
    - service mariadb start
    - service postgresql start
    - sleep 5
    # run tests
    - build/linux-release/test/AllTestsInMain
    # shutdown service
    - service mariadb stop
    - service postgresql stop
    # make coverage reposts
    - mkdir -p build/coverage
    - gcovr --config gcovr-cobertura.cfg
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage/coverage.xml

pages:
  stage: deploy
  image: $CI_REGISTRY/libsese/sese-core:latest
  script:
    - doxygen
    - mv build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual