name: github pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/Doxyfile'
      - 'sese/**'
      - 'static/**'
      - 'README.md'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Build docs
        uses: SHIINASAMA/roxy@1.1
        with:
          DOXYFILE: 'docs/Doxyfile'
          RESOURCE_FOLDER: 'static'
          OUTPUT_FOLDER: 'build/html'

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html