name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Build docs
        uses: SHIINASAMA/roxy@1.0
        with:
          DOXYGEN_CONTEXT: '/github/workspace'
          DOXYFILE: 'docs/Doxyfile'
          PROJECT_PATH: '/github/workspace'
          OUTPUT_PATH: '/github/workspace/build/html'

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html