name: macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies(pip-ci)
        run: pip install -r ${{ github.workspace }}/ci/requirements.txt

      - name: Install Dependencies(pip-scripts)
        run: pip install -r ${{ github.workspace }}/scripts/requirements.txt

      - name: Check deps
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.unix_check

      - name: Cache Vcpkg Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.unix_config

      - name: Build
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.unix_build

      - name: Test
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.unix_test