name: macOS-brew

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'

      - name: Setup pip
        run: pip install -r ${{ github.workspace }}/requirements.txt

      - name: Setup deps
        working-directory: ${{ github.workspace }}
        run: ./scripts/install_darwin_deps.sh

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: >
          cmake
          -DCMAKE_BUILD_TYPE=Release
          -DSESE_BUILD_TEST=ON
          -DSESE_USE_NATIVE_MANAGER=ON
          -DSESE_USE_ARCHIVE=ON
          -DSESE_DB_USE_MARIADB=ON
          -DSESE_DB_USE_POSTGRES=ON
          -Bbuild

      - name: Build
        working-directory: ${{ github.workspace }}
        run: cmake --build build -- -j 2

      - name: Test
        working-directory: ${{ github.workspace }}
        run: build/sese/test/AllTestsInMain --gtest_filter=-TestMaria*:TestPostgres*:TestSqlite*