name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref_name }}
    steps:
      - name: Checksum
        run: |
          curl https://github/libsese/sese/archive/refs/${{ env.tag }}.zip -O sese.zip
          sha256sum sese.zip > sese-${{ env.tag }}.zip.sha256
          sha512sum sese.zip > sese-${{ env.tag }}.zip.sha512
          curl https://github/libsese/sese/archive/refs/${{ env.tag }}.tar.gz -O sese.tar.gz
          sha256sum sese.tar.gz > sese-${{ env.tag }}.tar.gz.sha256
          sha512sum sese.tar.gz > sese-${{ env.tag }}.tar.gz.sha512

      - name: Create release
        run: |
          gh release create "${{ env.tag }}" \
          sese-${{ env.tag }}.zip.sha256 \
          sese-${{ env.tag }}.zip.sha512 \
          sese-${{ env.tag }}.tar.gz.sha256 \
          sese-${{ env.tag }}.tar.gz.sha512 \
          --repo="$GITHUB_REPOSITORY" \
          --title="sese-core ${{ env.tag }} release" \
          --generate-notes
