name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checksum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          curl https://github/libsese/sese/archive/refs/${tag}.zip -O sese.zip
          sha256sum sese.zip > sese-${tag}.zip.sha256
          sha512sum sese.zip > sese-${tag}.zip.sha512
          curl https://github/libsese/sese/archive/refs/${tag}.tar.gz -O sese.tar.gz
          sha256sum sese.tar.gz > sese-${tag}.tar.gz.sha256
          sha512sum sese.tar.gz > sese-${tag}.tar.gz.sha512

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
          sese-${tag}.zip.sha256 \
          sese-${tag}.zip.sha512 \
          sese-${tag}.tar.gz.sha256 \
          sese-${tag}.tar.gz.sha512 \
          --repo="$GITHUB_REPOSITORY" \
          --title="sese-core ${tag} release" \
          --generate-notes
