name: release

on:
  push:
    tags:
      - "*.*.*"
  workflow_run:
    workflows:
      - x64-linux-package
      - x64-osx-package
      - x64-windows-package
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref_name }}
    steps:
      - name: Checksum
        run: |
          wget https://github.com/libsese/sese/archive/refs/tags/${{ env.tag }}.zip -O sese-${{ env.tag }}.zip
          sha256sum sese-${{ env.tag }}.zip > sese-${{ env.tag }}.zip.sha256
          sha512sum sese-${{ env.tag }}.zip > sese-${{ env.tag }}.zip.sha512
          wget https://github.com/libsese/sese/archive/refs/tags/${{ env.tag }}.tar.gz -O sese-${{ env.tag }}.tar.gz
          sha256sum sese-${{ env.tag }}.tar.gz > sese-${{ env.tag }}.tar.gz.sha256
          sha512sum sese-${{ env.tag }}.tar.gz > sese-${{ env.tag }}.tar.gz.sha512

      - name: Create release
        run: |
          gh release create "${{ env.tag }}" \
          sese-${{ env.tag }}.zip.sha256 \
          sese-${{ env.tag }}.zip.sha512 \
          sese-${{ env.tag }}.tar.gz.sha256 \
          sese-${{ env.tag }}.tar.gz.sha512 \
          --repo="$GITHUB_REPOSITORY" \
          --title="sese-core ${{ env.tag }} release" \
          --generate-notes \
          ${{ (contains(env.tag, 'alpha') || contains(env.tag, 'beta')) && '--prerelease' || '' }}
