name: Ubuntu

on:
  push:
    branches:
      - main
      - stable
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_FLAGS="--coverage -fprofile-update=atomic" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSESE_BUILD_TEST=ON -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j4

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --extra-verbose

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies(pip)
        run: pip install -r ${{github.workspace}}/scripts/requirements.txt

      - name: Coverage
        working-directory: ${{github.workspace}}
        run: python3 ${{github.workspace}}/scripts/make_coverage_report.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CoverageReport
          path: ${{github.workspace}}/coverage