name: ubuntu-database

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-db:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies(pip-ci)
        run: pip install -r ${{ github.workspace }}/ci/requirements.txt

      - name: Install Dependencies(pip-scripts)
        run: pip install -r ${{ github.workspace }}/scripts/requirements.txt

      - name: Check deps
        working-directory: ${{ github.workspace }}
        run: sudo apt build-dep .

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: cmake -DCMAKE_BUILD_TYPE=Release -DSESE_BUILD_TEST=ON -DSESE_USE_NATIVE_MANAGER=ON -DSESE_DB_USE_MARIADB=ON -DSESE_DB_USE_POSTGRES=ON -DSESE_GITHUB_WORKFLOW=ON -Bbuild

      - name: Build
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.unix_build

      - name: Run Sqlite Scripts
        working-directory: ${{ github.workspace }}
        run: sqlite3 build/db_test.db < docker/sqlite_dump.sql

      - name: TestSqlite
        working-directory: ${{ github.workspace }}
        run: build/gtest-db/TestSqlite

      - name: Setup MySQL
        working-directory: ${{ github.workspace }}
        run: sudo systemctl start mysql.service && \
             sudo mysql -uroot -proot < docker/mysql_dump.sql

      - name: TestMaria
        working-directory: ${{ github.workspace }}
        run: build/gtest-db/TestMaria

      - name: Stop MySQL
        run: sudo systemctl stop mysql.service

      - name: Setup Postgres
        run: sudo systemctl start postgresql.service && \
             sudo psql -f docker/postgres_dump.sql

      - name: TestPostgres
        working-directory: ${{ github.workspace }}
        run: build/gtest-db/TestPostgres

      - name: Stop Postgres
        run: sudo systemctl stop postgresql.service