name: windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: Install Dependencies(pip-ci)
        run: pip install -r ${{ github.workspace }}/ci/requirements.txt

      - name: Install Dependencies(pip-scripts)
        run: pip install -r ${{ github.workspace }}/scripts/requirements.txt

      - name: Check deps
        working-directory: ${{ github.workspace }}
        run: python -m ci.win_check

      - name: Cache Vcpkg Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1

      - name: Requiring CL
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: python -m ci.win_config

      - name: Build
        working-directory: ${{ github.workspace }}
        run: python -m ci.win_build

      - name: Test
        working-directory: ${{ github.workspace }}
        run: python -m ci.win_test

