name: Windows-MinGW64

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies(pip)
        run: pip install -r ${{github.workspace}}/scripts/requirements.txt

      - name: Cache Vcpkg Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ runner.os }}-mingw64-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: Update Env
        run: |
          $env:PATH = "C:/msys64/usr/bin;$env:PATH"
          echo $env:PATH

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSESE_BUILD_TEST=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-mingw-dynamic -DCMAKE_C_COMPILER=C:/msys64/usr/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/msys64/usr/bin/g++.exe

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 8

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --extra-verbose