name: windows

on:
  pull_request:
    paths:
      - 'sese/**'
      - 'CMakeLists.txt'
      - 'vcpkg.json'
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Setup Pip
        run: |
          pip install -r requirements.txt

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1

      - name: Requiring CL
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Restore Vcpkg Cache
        uses: actions/cache@v4.1.2
        with:
          path: ${{ github.workspace }}/vcpkg-archive
          key: vcpkg-windows-x64

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        env:
          VCPKG_ROOT: C:/vcpkg
          VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-archive
        run: >
          mkdir -Force vcpkg-archive &&
          cmake -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DPython3_EXECUTABLE=C:/hostedtoolcache/windows/Python/3.11.9/x64/python3.exe
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
          -DSESE_BUILD_TEST=ON
          -DSESE_USE_ARCHIVE=ON
          -Bbuild

      - name: Build
        working-directory: ${{ github.workspace }}
        run: cmake --build build -- -j 2

      - name: Test
        working-directory: ${{ github.workspace }}
        run: |
          build/sese/test/AllTestsInMain --gtest_filter=-TestMaria*:TestPostgres*:TestSqlite* --gtest_output="xml:build/test_report.xml"

      - name: Test report
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: JEST Tests on Windows
          path: build/test_report.xml
          reporter: jest-junit
