name: windows

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
            python-version: '3.11'

      - name: Setup pip
        run: pip install -r ${{ github.workspace }}/requirements.txt

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1

      - name: Requiring CL
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DSESE_BUILD_TEST=ON -DSESE_USE_ARCHIVE=ON -Bbuild

      - name: Build
        working-directory: ${{ github.workspace }}
        run: cmake --build build -- -j 2

      - name: Test
        working-directory: ${{ github.workspace }}
        run: build/sese/test/AllTestsInMain --gtest_filter=-TestMaria*:TestPostgres*:TestSqlite* --gtest_output="xml:build/test_report.xml"

      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests on Windows
          path: build/test_report.xml
          reporter: jest-junit