name: windows-package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  x64-osx:
    runs-on: windows-2022
    strategy:
      matrix:
        triplet: ['x64-windows']
    env:
      VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Requiring CL
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Config
        working-directory: ${{ github.workspace }}/package
        run: >
          cmake
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          -B build

      - name: Build
        working-directory: ${{ github.workspace }}/package
        run: >
          cmake --build build